<?php
/**
 * setup.php - Smart Installer for Garda (Professional Edition)
 */

if (file_exists(__DIR__ . '/config/config.php')) {
    die("
    <div style='font-family: sans-serif; text-align: center; padding: 100px; background: #09090b; color: #fff; height: 100vh; box-sizing: border-box;'>
        <h1 style='color: #ef4444;'>Security Block: System Already Installed</h1>
        <p style='color: #a1a1aa;'>Untuk alasan keamanan, installer ini telah dikunci.</p>
        <p style='font-size: 0.8rem; color: #71717a;'>Jika Anda benar-benar ingin menginstall ulang, hapus file <code>config/config.php</code> secara manual.</p>
        <br>
        <a href='public/index.php' style='color: #6366f1; text-decoration: none; font-weight: bold;'>&larr; Balik ke Dashboard</a>
    </div>
    ");
}

$error = '';
$success = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $db_host = $_POST['db_host'] ?? 'localhost';
    $db_user = $_POST['db_user'] ?? 'root';
    $db_pass = $_POST['db_pass'] ?? '';
    $db_name = $_POST['db_name'] ?? 'garda_db';
    
    $admin_user = $_POST['admin_user'] ?? 'admin';
    $admin_pass = $_POST['admin_pass'] ?? 'admin123';

    try {
        // 1. Database Connection & Creation
        $pdo = new PDO("mysql:host=$db_host", $db_user, $db_pass);
        $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        $pdo->exec("CREATE DATABASE IF NOT EXISTS `$db_name` character set utf8mb4 collate utf8mb4_unicode_ci");
        $pdo->exec("USE `$db_name` ");

        // 2. Multi-Mode Schema Import (File Upload or Internal Default)
        $sqlSchema = '';
        if (isset($_FILES['schema_file']) && $_FILES['schema_file']['error'] === UPLOAD_ERR_OK) {
            $sqlSchema = file_get_contents($_FILES['schema_file']['tmp_name']);
        } else {
            // Internal Default if no file uploaded
            $defaultSchemaPath = __DIR__ . '/db/schema.sql';
            if (file_exists($defaultSchemaPath)) {
                $sqlSchema = file_get_contents($defaultSchemaPath);
            } else {
                throw new Exception("Default schema.sql tidak ditemukan dan tidak ada file yang diupload.");
            }
        }

        if (empty($sqlSchema)) {
            throw new Exception("SQL Schema kosong atau tidak terbaca.");
        }

        // Execute SQL - Robust multi-statement execution
        $queries = explode(';', $sqlSchema);
        foreach ($queries as $query) {
            $query = trim($query);
            if (!empty($query)) $pdo->exec($query);
        }

        // 3. Create Master Admin (This happens AFTER schema import to ensure table exists)
        $hash = password_hash($admin_pass, PASSWORD_BCRYPT);
        // Check if table users exists first (safety)
        $stmt = $pdo->prepare("INSERT INTO users (username, password_hash, role) VALUES (?, ?, 'admin') ON DUPLICATE KEY UPDATE password_hash = VALUES(password_hash)");
        $stmt->execute([$admin_user, $hash]);

        $roles = [['mahasiswa', 'mhs123', 'mahasiswa'], ['dosen', 'dosen123', 'dosen'], ['mitra', 'mitra123', 'mitra']];
        foreach($roles as $r) {
            $h = password_hash($r[1], PASSWORD_BCRYPT);
            $stmt = $pdo->prepare("INSERT IGNORE INTO users (username, password_hash, role) VALUES (?, ?, ?)");
            $stmt->execute([$r[0], $h, $r[2]]);
        }

        // 4. Config Generation (Absolute Base URL Detection)
        $protocol = isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http";
        $host = $_SERVER['HTTP_HOST'];
        $path = str_replace('setup.php', '', $_SERVER['REQUEST_URI']);
        $baseUrl = "{$protocol}://{$host}{$path}";

        $configContent = "<?php
/**
 * Global Configuration - Generated by Smart Setup
 */
define('APP_NAME', 'GARDA');
define('BASE_URL', '$baseUrl');

define('DB_HOST', '$db_host');
define('DB_NAME', '$db_name');
define('DB_USER', '$db_user');
define('DB_PASS', '$db_pass');

define('AUTH_SALT', '" . bin2hex(random_bytes(16)) . "');

if (session_status() === PHP_SESSION_NONE) {
    ini_set('session.cookie_httponly', 1);
    ini_set('session.use_only_cookies', 1);
}
";
        if (!is_dir(__DIR__ . '/config')) mkdir(__DIR__ . '/config');
        file_put_contents(__DIR__ . '/config/config.php', $configContent);

        $success = "Instalasi Berhasil! Database & Akun Default Siap.";

    } catch (Exception $e) {
        $error = "FATAL ERROR: " . $e->getMessage();
    }
}
?>
<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <title>Garda Smart Setup</title>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;800&display=swap" rel="stylesheet">
    <style>
        :root { --p: #6366f1; --bg: #09090b; --card: #18181b; --border: #27272a; }
        body { background: var(--bg); color: #fff; font-family: 'Plus Jakarta Sans', sans-serif; display: flex; align-items: center; justify-content: center; min-height: 100vh; margin: 0; padding: 20px; }
        .card { background: var(--card); padding: 40px; border-radius: 24px; border: 1px solid var(--border); width: 100%; max-width: 550px; box-shadow: 0 25px 50px -12px rgba(0,0,0,0.5); }
        h1 { font-weight: 800; letter-spacing: -0.05em; margin-bottom: 5px; text-align: center; }
        .subtitle { text-align: center; color: #a1a1aa; font-size: 0.9rem; margin-bottom: 30px; }
        .form-section { background: rgba(0,0,0,0.2); padding: 20px; border-radius: 12px; margin-bottom: 20px; border: 1px solid var(--border); }
        .section-title { font-size: 0.75rem; font-weight: 800; color: var(--p); text-transform: uppercase; margin-bottom: 15px; display: flex; align-items: center; gap: 8px; }
        .form-group { margin-bottom: 15px; }
        label { display: block; font-size: 0.75rem; color: #a1a1aa; margin-bottom: 6px; }
        input[type="text"], input[type="password"], input[type="file"] { width: 100%; background: var(--bg); border: 1px solid var(--border); padding: 12px; border-radius: 10px; color: #fff; font-size: 0.9rem; box-sizing: border-box; transition: 0.3s; }
        input:focus { border-color: var(--p); outline: none; box-shadow: 0 0 0 3px rgba(99, 102, 241, 0.2); }
        .file-info { font-size: 0.7rem; color: #71717a; margin-top: 5px; font-style: italic; }
        .btn { width: 100%; background: var(--p); border: none; padding: 16px; border-radius: 12px; color: #fff; font-weight: 700; cursor: pointer; transition: 0.3s; margin-top: 10px; font-size: 1rem; }
        .btn:hover { background: #4f46e5; transform: translateY(-2px); }
        .alert { padding: 15px; border-radius: 12px; margin-bottom: 20px; font-size: 0.875rem; line-height: 1.5; }
        .alert-error { background: rgba(239, 68, 68, 0.1); color: #f87171; border: 1px solid rgba(239, 68, 68, 0.2); }
        .alert-success { background: rgba(16, 185, 129, 0.1); color: #34d399; border: 1px solid rgba(16, 185, 129, 0.2); text-align: center; }
    </style>
</head>
<body>
<div class="card">
    <h1>GARDA Initial Setup</h1>
    <p class="subtitle">Quick system initialization & database deployment</p>
    
    <?php if ($error): ?> <div class="alert alert-error">❌ <?= $error ?></div> <?php endif; ?>
    <?php if ($success): ?> 
        <div class="alert alert-success">✅ <?= $success ?></div>
        <a href="public/index.php" class="btn" style="text-align:center; display:block; text-decoration:none;">Masuk ke Portal</a>
    <?php else: ?>

    <form method="POST" enctype="multipart/form-data">
        <div class="form-section">
            <div class="section-title">📡 Database Server</div>
            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 15px;">
                <div class="form-group">
                    <label>DB Host</label>
                    <input type="text" name="db_host" placeholder="localhost" value="localhost">
                </div>
                <div class="form-group">
                    <label>DB Name (Target)</label>
                    <input type="text" name="db_name" placeholder="garda_db" value="garda_db">
                </div>
            </div>
            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 15px;">
                <div class="form-group">
                    <label>User</label>
                    <input type="text" name="db_user" placeholder="root" value="root">
                </div>
                <div class="form-group">
                    <label>Password</label>
                    <input type="password" name="db_pass" placeholder="Password DB">
                </div>
            </div>
        </div>

        <div class="form-section">
            <div class="section-title">📂 Database Schema</div>
            <div class="form-group">
                <label>Upload .SQL File (Opsional)</label>
                <input type="file" name="schema_file" accept=".sql">
                <p class="file-info">*Jika kosong, sistem akan menggunakan file default di /db/schema.sql</p>
            </div>
        </div>

        <div class="form-section">
            <div class="section-title">🔑 Master Admin</div>
            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 15px;">
                <div class="form-group">
                    <label>Admin Username</label>
                    <input type="text" name="admin_user" value="admin">
                </div>
                <div class="form-group">
                    <label>Admin Password</label>
                    <input type="text" name="admin_pass" value="admin123">
                </div>
            </div>
        </div>

        <button type="submit" class="btn">🚀 Initialize System</button>
    </form>
    <?php endif; ?>
</div>
</body>
</html>
