<?php
/**
 * Global Configuration - Generated by Smart Setup
 */
define('APP_NAME', 'GARDA');
define('BASE_URL', 'http://localhost/github/Garda/');

define('DB_HOST', 'localhost');
define('DB_NAME', 'garda_dbac');
define('DB_USER', 'root');
define('DB_PASS', '');

define('AUTH_SALT', '1815660cc8042782b25da8c7a41ba3c3');

if (session_status() === PHP_SESSION_NONE) {
    ini_set('session.cookie_httponly', 1);
    ini_set('session.use_only_cookies', 1);
}
